### PR TITLE
Remove async from setter

### PR DESCRIPTION
**Pull request by niklhut**
Use the async versions of the bcrypt api with await instead of the sync versions since it is already in an async context.

### CODE REVIEW

**Review by suiluj482 — CHANGES_REQUESTED** [review]
On request (tried deleting database volume, npm i) ohne async geht dies
http://localhost:3000/api/addUser?name=Max&mail=max@gmail.com&password=max1234
ERROR [nuxt] [request error] [unhandled] [500] notNull Violation: User.passwordHash cannot be null
WARN  [Vue Router warn]: No match found for location with path "/api/addUser?name=Max&mail=max@gmail.com&password=max1234"

 WARN  [Vue Router warn]: No match found for location with path "/api/addUser"
 
 
Not the problem of this pr, but the endpoint return 500 when the email or user allready exists

**Comment by niklhut** [comment]
This is definitely an error from before, can you make a bug report issue and then we fix it there. I feel like this is outside the scope of this pr.

**Comment by Tim-Kroker** [comment]
> On request (tried deleting database volume, npm i) ohne async geht dies http://localhost:3000/api/addUser?name=Max&mail=max@gmail.com&password=max1234 ERROR [nuxt] [request error] [unhandled] [500] notNull Violation: User.passwordHash cannot be null WARN [Vue Router warn]: No match found for location with path "/api/addUser?name=Max&mail=[max@gmail.com](mailto:max@gmail.com)&password=max1234"
> 
> WARN [Vue Router warn]: No match found for location with path "/api/addUser"
> 
> Not the problem of this pr, but the endpoint return 500 when the email or user allready exists

This is the intended behavior. The endpoint is there in order to create new users via GET-parameters. Since username and email must be unique, one cannot create another user with the same username or email. One could catch the error thrown by the insert statement however such that the endpoint doesn't do anything in this case.

**Comment by niklhut** [comment]
Ok but since we anyways have to make new endpoints which don't use the query parameters but json i think this is already covered by #31

**Review by Tim-Kroker — CHANGES_REQUESTED** [review]
I request to just remove the async context and leave the sync methods. Async getters and setters are currently NOT supported: https://stackoverflow.com/questions/22002698/sequelize-custom-setter-doesnt-set

This took me 3 hours to realize

**Comment by niklhut** [comment]
No, actually there are two problems, one is as @Tim-Kroker said intended behavior and the other one comes from the async setter. It does in fact not work and throw the passwordHash cannot be null error. So I guess it is wrong to use async setters

**Comment by niklhut** [comment]
Ok so I removed the async keyword in front of the setter now, this should solve the confusion and error

**Review by Tim-Kroker — DISMISSED** [review]
lgtm

**Comment by suiluj482** [comment]
> > On request (tried deleting database volume, npm i) ohne async geht dies http://localhost:3000/api/addUser?name=Max&mail=max@gmail.com&password=max1234 ERROR [nuxt] [request error] [unhandled] [500] notNull Violation: User.passwordHash cannot be null WARN [Vue Router warn]: No match found for location with path "/api/addUser?name=Max&mail=[max@gmail.com](mailto:max@gmail.com)&password=max1234"
> > WARN [Vue Router warn]: No match found for location with path "/api/addUser"
> > Not the problem of this pr, but the endpoint return 500 when the email or user allready exists
> 
> This is the intended behavior. The endpoint is there in order to create new users via GET-parameters. Since username and email must be unique, one cannot create another user with the same username or email. One could catch the error thrown by the insert statement however such that the endpoint doesn't do anything in this case.

It is, but it shouldn't be a 500 error becouse it isnt a server error but bad parameters

**Review by suiluj482 — APPROVED** [review]
lgtm

**Pull request merged**
