### PR TITLE
implemented model associations & migration for User

### PR DESCRIPTION
**Pull request by Tim-Kroker**
- Implemented relations between models
- Used the default behavior for onDelete and onUpdate cases (see https://sequelize.org/docs/v7/associations/faq/#ondelete-and-onupdate)
- Added a migration and seed for the user model

### CODE REVIEW

**Comment by Tim-Kroker** [comment]
> Migrations seem to work for me, just the logging did not, I created a PR (#68) to fix this. But the password in the seed does not seem to be hashed automatically, we will need to do that ourselves in the seed.

The creation of the first admin user must further be discussed. I don't like the idea of hard-coding an e-mail and password in the seed file.

**Comment by niklhut** [comment]
> The creation of the first admin user must further be discussed. I don't like the idea of hard-coding an e-mail and password in the seed file.

I agree that this is not optimal and we should change it later on with a separate onboarding screen, but I think for the beginning it is best to have something hardcoded.

**Review by niklhut — DISMISSED** [review]
LGTM

**Review by niklhut — APPROVED** [review]
LGTM

**Pull request merged**
